# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control
# Build directory: /Users/william/Documents/ns-allinone-3.37/ns-3.37/cmake-cache/examples/traffic-control
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-traffic-control "ns3.37-traffic-control-debug")
set_tests_properties(ctest-traffic-control PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control/CMakeLists.txt;1;build_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-queue-discs-benchmark "ns3.37-queue-discs-benchmark-debug")
set_tests_properties(ctest-queue-discs-benchmark PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control/CMakeLists.txt;12;build_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-fengadaptive "ns3.37-red-vs-fengadaptive-debug")
set_tests_properties(ctest-red-vs-fengadaptive PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control/CMakeLists.txt;24;build_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-nlred "ns3.37-red-vs-nlred-debug")
set_tests_properties(ctest-red-vs-nlred PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control/CMakeLists.txt;35;build_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-tbf-example "ns3.37-tbf-example-debug")
set_tests_properties(ctest-tbf-example PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control/CMakeLists.txt;46;build_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-cobalt-vs-codel "ns3.37-cobalt-vs-codel-debug")
set_tests_properties(ctest-cobalt-vs-codel PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control/CMakeLists.txt;56;build_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/examples/traffic-control/CMakeLists.txt;0;")
