# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-3.37/src/network/examples
# Build directory: /Users/william/Documents/ns-3.37/cmake-cache/src/network/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bit-serializer "ns3.37-bit-serializer-optimized")
set_tests_properties(ctest-bit-serializer PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/network/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/network/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-3.37/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-header "ns3.37-main-packet-header-optimized")
set_tests_properties(ctest-main-packet-header PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/network/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/network/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-3.37/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-tag "ns3.37-main-packet-tag-optimized")
set_tests_properties(ctest-main-packet-tag PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/network/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/network/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-3.37/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-packet-socket-apps "ns3.37-packet-socket-apps-optimized")
set_tests_properties(ctest-packet-socket-apps PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/network/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/network/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-3.37/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-lollipop-comparisions "ns3.37-lollipop-comparisions-optimized")
set_tests_properties(ctest-lollipop-comparisions PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/network/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/network/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-3.37/src/network/examples/CMakeLists.txt;0;")
