# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-3.37/src/energy/examples
# Build directory: /Users/william/Documents/ns-3.37/cmake-cache/src/energy/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-li-ion-energy-source "ns3.37-li-ion-energy-source-optimized")
set_tests_properties(ctest-li-ion-energy-source PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/energy/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/energy/examples/CMakeLists.txt;1;build_lib_example;/Users/william/Documents/ns-3.37/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-rv-battery-model-test "ns3.37-rv-battery-model-test-optimized")
set_tests_properties(ctest-rv-battery-model-test PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/energy/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/energy/examples/CMakeLists.txt;8;build_lib_example;/Users/william/Documents/ns-3.37/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-basic-energy-model-test "ns3.37-basic-energy-model-test-optimized")
set_tests_properties(ctest-basic-energy-model-test PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/energy/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/energy/examples/CMakeLists.txt;17;build_lib_example;/Users/william/Documents/ns-3.37/src/energy/examples/CMakeLists.txt;0;")
