# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-3.37/src/internet/examples
# Build directory: /Users/william/Documents/ns-3.37/cmake-cache/src/internet/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-main-simple "ns3.37-main-simple-optimized")
set_tests_properties(ctest-main-simple PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/internet/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/internet/examples/CMakeLists.txt;1;build_lib_example;/Users/william/Documents/ns-3.37/src/internet/examples/CMakeLists.txt;0;")
add_test(ctest-neighbor-cache-example "ns3.37-neighbor-cache-example-optimized")
set_tests_properties(ctest-neighbor-cache-example PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/internet/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/internet/examples/CMakeLists.txt;10;build_lib_example;/Users/william/Documents/ns-3.37/src/internet/examples/CMakeLists.txt;0;")
add_test(ctest-neighbor-cache-dynamic "ns3.37-neighbor-cache-dynamic-optimized")
set_tests_properties(ctest-neighbor-cache-dynamic PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/internet/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/internet/examples/CMakeLists.txt;20;build_lib_example;/Users/william/Documents/ns-3.37/src/internet/examples/CMakeLists.txt;0;")
