# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-3.37/scratch
# Build directory: /Users/william/Documents/ns-3.37/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_main-propagation-loss "ns3.37-main-propagation-loss-optimized")
set_tests_properties(ctest-scratch_main-propagation-loss PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch-simulator "ns3.37-scratch-simulator-optimized")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_test "ns3.37-test-optimized")
set_tests_properties(ctest-scratch_test PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_mimo-system-test_test "ns3.37-test-optimized")
set_tests_properties(ctest-scratch_mimo-system-test_test PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/scratch/mimo-system-test/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;89;create_scratch;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_my-antenna-model_test-my-antenna-model "ns3.37-test-my-antenna-model-optimized")
set_tests_properties(ctest-scratch_my-antenna-model_test-my-antenna-model PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/scratch/my-antenna-model/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;89;create_scratch;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3.37-scratch-subdir-optimized")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/scratch/subdir/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;89;create_scratch;/Users/william/Documents/ns-3.37/scratch/CMakeLists.txt;0;")
