# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-allinone-3.37/ns-3.37/src/buildings/examples
# Build directory: /Users/william/Documents/ns-allinone-3.37/ns-3.37/cmake-cache/src/buildings/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-buildings-pathloss-profiler "ns3.37-buildings-pathloss-profiler-debug")
set_tests_properties(ctest-buildings-pathloss-profiler PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/src/buildings/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/buildings/examples/CMakeLists.txt;1;build_lib_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/buildings/examples/CMakeLists.txt;0;")
add_test(ctest-outdoor-group-mobility-example "ns3.37-outdoor-group-mobility-example-debug")
set_tests_properties(ctest-outdoor-group-mobility-example PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/src/buildings/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/buildings/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/buildings/examples/CMakeLists.txt;0;")
add_test(ctest-outdoor-random-walk-example "ns3.37-outdoor-random-walk-example-debug")
set_tests_properties(ctest-outdoor-random-walk-example PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/src/buildings/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/buildings/examples/CMakeLists.txt;17;build_lib_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/buildings/examples/CMakeLists.txt;0;")
