# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-3.37/src/csma/examples
# Build directory: /Users/william/Documents/ns-3.37/cmake-cache/src/csma/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-csma-one-subnet "ns3.37-csma-one-subnet-optimized")
set_tests_properties(ctest-csma-one-subnet PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/csma/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/csma/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-3.37/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-broadcast "ns3.37-csma-broadcast-optimized")
set_tests_properties(ctest-csma-broadcast PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/csma/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/csma/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-3.37/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-packet-socket "ns3.37-csma-packet-socket-optimized")
set_tests_properties(ctest-csma-packet-socket PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/csma/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/csma/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-3.37/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-multicast "ns3.37-csma-multicast-optimized")
set_tests_properties(ctest-csma-multicast PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/csma/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/csma/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-3.37/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-raw-ip-socket "ns3.37-csma-raw-ip-socket-optimized")
set_tests_properties(ctest-csma-raw-ip-socket PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/csma/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/csma/examples/CMakeLists.txt;21;build_lib_example;/Users/william/Documents/ns-3.37/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-ping "ns3.37-csma-ping-optimized")
set_tests_properties(ctest-csma-ping PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-3.37/build/src/csma/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-3.37/src/csma/examples/CMakeLists.txt;31;build_lib_example;/Users/william/Documents/ns-3.37/src/csma/examples/CMakeLists.txt;0;")
