# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-allinone-3.37/ns-3.37/src/nix-vector-routing/examples
# Build directory: /Users/william/Documents/ns-allinone-3.37/ns-3.37/cmake-cache/src/nix-vector-routing/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-nix-simple "ns3.37-nix-simple-debug")
set_tests_properties(ctest-nix-simple PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/nix-vector-routing/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/nix-vector-routing/examples/CMakeLists.txt;0;")
add_test(ctest-nix-simple-multi-address "ns3.37-nix-simple-multi-address-debug")
set_tests_properties(ctest-nix-simple-multi-address PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/nix-vector-routing/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/nix-vector-routing/examples/CMakeLists.txt;0;")
add_test(ctest-nms-p2p-nix "ns3.37-nms-p2p-nix-debug")
set_tests_properties(ctest-nms-p2p-nix PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/nix-vector-routing/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/nix-vector-routing/examples/CMakeLists.txt;0;")
add_test(ctest-nix-double-wifi "ns3.37-nix-double-wifi-debug")
set_tests_properties(ctest-nix-double-wifi PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/nix-vector-routing/examples/CMakeLists.txt;22;build_lib_example;/Users/william/Documents/ns-allinone-3.37/ns-3.37/src/nix-vector-routing/examples/CMakeLists.txt;0;")
